server:
  port: 9999
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: zpoa
  datasource:
    url: jdbc:mysql://localhost/zpoa?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**